# Generated by Django 5.2.4 on 2025-07-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_app', '0002_rename_conocimientos_conocimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('Básico', 'Básico'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado'), ('Experto', 'Experto')], max_length=50)),
            ],
        ),
    ]
